/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mao_easyjokejava_uitl_PatchUtils */

#ifndef _Included_com_mao_easyjokejava_uitl_PatchUtils
#define _Included_com_mao_easyjokejava_uitl_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
#include <malloc.h>
int mydiff(int argc,char *argv[]);
int mypatch(int argc,char * argv[]);
/*
 * Class:     com_mao_easyjokejava_uitl_PatchUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mao_easyjokejava_uitl_PatchUtils_diff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_mao_easyjokejava_uitl_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mao_easyjokejava_uitl_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
