/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hc_essay_library_util_NDKTools */

#ifndef _Included_com_hc_essay_library_util_NDKTools
#define _Included_com_hc_essay_library_util_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hc_essay_library_util_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hc_essay_library_util_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
